# based on https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#configuration
# from running `helm show values prometheus-community/kube-prometheus-stack`

prometheus:
  prometheusSpec:
    retention: 1d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi

    additionalScrapeConfigs:
    - job_name: "kubernetes-services"
      kubernetes_sd_configs:
        - role: service
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
