kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: druid-cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /tmp/druid-data
    containerPath: /tmp/druid-data
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  - containerPort: 30888
    hostPort: 8888
    protocol: TCP
- role: worker
  extraMounts:
  - hostPath: /tmp/druid-data
    containerPath: /tmp/druid-data
- role: worker
  extraMounts:
  - hostPath: /tmp/druid-data
    containerPath: /tmp/druid-data 
