apiVersion: v1
kind: Service
metadata:
  labels:
    druid-cluster: local
  name: druid-metrics
  namespace: druid
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: druid
  type: ClusterIP
